{{- if .Values.rds.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rds.secretName }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  username: {{ .Values.rds.secret.username | b64enc }}
  password: {{ .Values.rds.secret.password | b64enc }}
{{- end }}

